### ISSUE TITLE
URL for current stock price is broken

### ISSUE THREAD

**Issue by rogerallen** [rogerallen/stockpredictr#6]
From the code, we knew this day would come eventually:

```
  # FIXME -- eventually google finance will go away?
  stock_price_url = "http://finance.google.com/finance/info?client=ig&q=%s" % (symbol)
```

And now, checking 

http://finance.google.com/finance/info?client=ig&q=NVDA

returns 404.  Oh no!

**Comment by rogerallen** [comment]
Yay, there is a simple change/fix.

https://stackoverflow.com/questions/46070126/google-finance-json-stock-quote-stopped-working

Just a slight change to the URL & the JSON data is the same (at least the bit I used)

**Comment by rogerallen** [comment]
Darn.  It seems this has become an issue again.  asking for JSON gives a redirect to an HTML page.

HandleContest GET Error (/base/data/home/apps/s~stockpredictr-hrd/10.405313349926355659/stockpredictr_views.py:220)
Traceback (most recent call last):
  File "/base/data/home/apps/s~stockpredictr-hrd/10.405313349926355659/stockpredictr_views.py", line 174, in get
    stock_price = get_stock_price(contest.stock_symbol)
  File "/base/data/home/apps/s~stockpredictr-hrd/10.405313349926355659/stockpredictr_models.py", line 154, in get_stock_price
    stock = get_stock_from_symbol(symbol)
  File "/base/data/home/apps/s~stockpredictr-hrd/10.405313349926355659/stockpredictr_models.py", line 128, in get_stock_from_symbol
    symbol)
  File "/base/data/home/apps/s~stockpredictr-hrd/10.405313349926355659/stockpredictr_models.py", line 109, in get_stock_from_db
    stock.recent_price = get_stock_price_from_web(symbol)
  File "/base/data/home/apps/s~stockpredictr-hrd/10.405313349926355659/stockpredictr_models.py", line 173, in get_stock_price_from_web
    stock_data = json.loads(tmp)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_dist/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_dist/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_dist/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by rogerallen** [comment]
So, right off, I need to handle the ValueError Exception so the site is not flat-broken.

Next, I need to find another way to update the stock price.

**Comment by rogerallen** [comment]
Oh, this looks like a good replacement: https://iextrading.com/developer/docs/#quote

For example: https://api.iextrading.com/1.0/stock/ibm/quote gives:

```
{"symbol":"IBM","companyName":"International Business Machines Corporation","primaryExchange":"New York Stock Exchange","sector":"Technology","calculationPrice":"tops",
"open":145.03,"openTime":1524490210226,"close":144.9,"closeTime":1524254592582,"high":145.96,"low":144.33,"latestPrice":145.35,"latestSource":"IEX real time price",
"latestTime":"2:38:10 PM","latestUpdate":1524508690646,"latestVolume":3352527,"iexRealtimePrice":145.35,"iexRealtimeSize":100,"iexLastUpdated":1524508690646,"delayedPrice":145.3,"delayedPriceTime":1524508002624,
"previousClose":144.9,"change":0.45,"changePercent":0.00311,"iexMarketPercent":0.01405,"iexVolume":47103,"avgTotalVolume":5401551,"iexBidPrice":141.98,
"iexBidSize":100,"iexAskPrice":145.41,"iexAskSize":100,"marketCap":133891753393,"peRatio":10.46,"week52High":171.13,"week52Low":139.13,"ytdChange":-0.04965167686769093}
```

**Comment by rogerallen** [comment]
iextrading has changed their API.  Cannot see if there is an equivalent to https://api.iextrading.com/1.0/stock/NVDA/quote at the moment, but this needs to be investigated & resolved.

**Comment by rogerallen** [comment]
https://rapidapi.com/blog/best-stock-api/

Found this site is 800 queries per day for free https://rapidapi.com/twelvedata/api/twelve-data1/pricing

this is 100k queries /month https://rapidapi.com/amansharma2910/api/realstonks 1M is $5/mo

500/day at 
https://rapidapi.com/alphavantage/api/alpha-vantage/pricing
